# Generated by Django 2.2.10 on 2020-07-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200727_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Текст'), ('one_option', 'Один вариант'), ('several_options', 'Несколько вариантов')], default='text', max_length=16),
        ),
    ]
